"""
Django settings for csr_enterprise project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9*f9kh@6-ou9euv+=u_*3te6p9p9@jwne5kbj2w*c_$vh&&l8$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'service_dashboard',
    'events',
    'accounts',
    'notifications',
    'jazzmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'csr_enterprise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'csr_enterprise.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Redirect to the homepage (Dashboard) after login
LOGIN_REDIRECT_URL = 'smart_redirect'

# Redirect to the homepage after logout
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Add your custom middleware here:
    'service_dashboard.middleware.RequestLogMiddleware',  # <--- NEW LINE
]

JAZZMIN_SETTINGS = {
    "site_title": "CSR Admin",
    "site_header": "CSR Connect",
    "site_brand": "CSR Management",
    
    # Add your custom views to the sidebar
    "custom_links": {
        # The "" means these links will appear at the very top level of the menu
        "": [
            {
                "name": "📸 Scan Ticket", 
                "url": "scanner_prototype", # Matches your urls.py name
                "permissions": ["auth.view_user"]
            },
            {
                "name": "📢 Broadcasts", 
                "url": "notifications", # Matches your urls.py name
                "permissions": ["auth.view_user"]
            }
        ]
    },
    
    # Optional: Tweak the UI theme 
    "theme": "flatly",
}

JAZZMIN_SETTINGS = {
    "site_title": "CSR Admin",
    "site_header": "CSR Connect",
    "site_brand": "CSR Management",
    
    # This injects your custom views into the Jazzmin sidebar
    "custom_links": {
        "service_dashboard": [
            {
                "name": "📊 Dashboard Stats", 
                "url": "admin_dashboard", 
                "icon": "fas fa-chart-line",
            },
            {
                "name": "📸 Scan Ticket (Beta)", 
                "url": "scanner_prototype", 
                "icon": "fas fa-camera",
            },
            {
                "name": "📢 Broadcasts", 
                "url": "notifications", 
                "icon": "fas fa-bullhorn",
            }
        ]
    },
    
    # Optional: Makes the UI look a bit more modern
    "theme": "litera", 
}